import { vars } from 'nativewind'

export type ThemeColors = {
  af: string,
  as: string,
  background: {
    blur: string,
    primary: string,
    quaternary: string,
    secondary: string,
    tertiary: string
  },
  error: string,
  eu: string,
  info: string,
  na: string,
  oc: string,
  onPrimary100: string,
  onPrimary20: string,
  onPrimary30: string,
  onPrimary50: string,
  onPrimary70: string,
  primary100: string,
  primary30: string,
  primary50: string,
  primary70: string,
  sa: string,
  secondary100: string,
  secondary15: string,
  secondary30: string,
  secondary50: string,
  success: string
  tertiary100: string,
  tertiary30: string,
  tertiary50: string,
  text100: string,
  text30: string,
  text50: string,
  text70: string,
  text90: string,
  warning: string
}

const baseColors: Record<'light' | 'dark', ThemeColors> = {
  dark: {
    af: '#4B1F99',
    as: '#8B1717',
    background: {
      blur: '#00000099',
      primary: '#000000',
      quaternary: '#3A3A3C',
      secondary: '#1C1C1E',
      tertiary: '#2C2C2E',
    },
    error: '#DC2626',

    eu: '#1E40AF',
    info: '#1E40AF',
    na: '#024731',
    oc: '#6F0F3D',

    onPrimary100: '#FFFFFF',
    onPrimary20: '#FFFFFF33',
    onPrimary30: '#FFFFFF4D',

    onPrimary50: '#FFFFFF80',
    onPrimary70: '#FFFFFFB2',
    primary100: '#1E40AF',
    primary30: '#1E40AF4D',
    primary50: '#1E40AF80',

    primary70: '#1E40AFB2',

    sa: '#8B2F00',
    secondary100: '#065F46',
    secondary15: '#10B981',
    secondary30: '#059669',
    secondary50: '#047857',

    success: '#047857',
    tertiary100: '#FF7849',
    tertiary30: '#FFAD85',
    tertiary50: '#FF9466',

    text100: '#FFFFFF',
    text30: '#FFFFFF4D',
    text50: '#FFFFFF80',
    text70: '#FFFFFFCC',
    text90: '#FFFFFFE5',
    warning: '#C2410C',
  },

  light: {
    af: '#C0B4E0',
    as: '#D9817E',
    background: {
      blur: '#FFFFFFCC',
      primary: '#FFFFFF',
      quaternary: '#D1D1D6',
      secondary: '#F2F2F7',
      tertiary: '#E5E5EA',
    },
    error: '#FCA5A5',

    eu: '#A8B8D1',
    info: '#93C5FD',
    na: '#9CCCBF',
    oc: '#D18FA1',

    onPrimary100: '#000000',
    onPrimary20: '#00000033',
    onPrimary30: '#0000004D',

    onPrimary50: '#00000080',
    onPrimary70: '#000000B2',
    primary100: '#B3D9FF',
    primary30: '#B3D9FF4D',
    primary50: '#B3D9FF80',

    primary70: '#B3D9FFB2',

    sa: '#D4CA55',
    secondary100: '#A3F3D0',
    secondary15: '#ECFDF5',
    secondary30: '#D1FAE5',
    secondary50: '#C2F5E0',

    success: '#86EFAC',
    tertiary100: '#FF6B35',
    tertiary30: '#FFAD66',
    tertiary50: '#FF8C42',

    text100: '#000000',
    text30: '#0000004D',
    text50: '#00000080',
    text70: '#000000C0',
    text90: '#000000E5',
    warning: '#FDE68A',
  },
}

export const themes = {
  dark: vars({
    '--color-af': baseColors.dark.af,
    '--color-as': baseColors.dark.as,
    '--color-background-blur': baseColors.dark.background.blur,
    '--color-background-primary': baseColors.dark.background.primary,
    '--color-background-quaternary': baseColors.dark.background.quaternary,
    '--color-background-secondary': baseColors.dark.background.secondary,
    '--color-background-tertiary': baseColors.dark.background.tertiary,
    '--color-error': baseColors.dark.error,
    '--color-eu': baseColors.dark.eu,
    '--color-info': baseColors.dark.info,
    '--color-na': baseColors.dark.na,
    '--color-oc': baseColors.dark.oc,
    '--color-onPrimary-100': baseColors.dark.onPrimary100,
    '--color-onPrimary-20': baseColors.dark.onPrimary20,
    '--color-onPrimary-30': baseColors.dark.onPrimary30,
    '--color-onPrimary-50': baseColors.dark.onPrimary50,
    '--color-onPrimary-70': baseColors.dark.onPrimary70,
    '--color-primary-100': baseColors.dark.primary100,
    '--color-primary-30': baseColors.dark.primary30,
    '--color-primary-50': baseColors.dark.primary50,
    '--color-primary-70': baseColors.dark.primary70,
    '--color-sa': baseColors.dark.sa,
    '--color-secondary-100': baseColors.dark.secondary100,
    '--color-secondary-15': baseColors.dark.secondary15,
    '--color-secondary-30': baseColors.dark.secondary30,
    '--color-secondary-50': baseColors.dark.secondary50,
    '--color-success': baseColors.dark.success,
    '--color-tertiary-100': baseColors.dark.tertiary100,
    '--color-tertiary-30': baseColors.dark.tertiary30,
    '--color-tertiary-50': baseColors.dark.tertiary50,
    '--color-text-100': baseColors.dark.text100,
    '--color-text-30': baseColors.dark.text30,
    '--color-text-50': baseColors.dark.text50,
    '--color-text-70': baseColors.dark.text70,
    '--color-text-90': baseColors.dark.text90,
    '--color-warning': baseColors.dark.warning,
  }),
  light: vars({
    '--color-af': baseColors.light.af,
    '--color-as': baseColors.light.as,
    '--color-background-blur': baseColors.light.background.blur,
    '--color-background-primary': baseColors.light.background.primary,
    '--color-background-quaternary': baseColors.light.background.quaternary,
    '--color-background-secondary': baseColors.light.background.secondary,
    '--color-background-tertiary': baseColors.light.background.tertiary,
    '--color-error': baseColors.light.error,
    '--color-eu': baseColors.light.eu,
    '--color-info': baseColors.light.info,
    '--color-na': baseColors.light.na,
    '--color-oc': baseColors.light.oc,
    '--color-onPrimary-100': baseColors.light.onPrimary100,
    '--color-onPrimary-20': baseColors.light.onPrimary20,
    '--color-onPrimary-30': baseColors.light.onPrimary30,
    '--color-onPrimary-50': baseColors.light.onPrimary50,
    '--color-onPrimary-70': baseColors.light.onPrimary70,
    '--color-primary-100': baseColors.light.primary100,
    '--color-primary-30': baseColors.light.primary30,
    '--color-primary-50': baseColors.light.primary50,
    '--color-primary-70': baseColors.light.primary70,
    '--color-sa': baseColors.light.sa,
    '--color-secondary-100': baseColors.light.secondary100,
    '--color-secondary-15': baseColors.light.secondary15,
    '--color-secondary-30': baseColors.light.secondary30,
    '--color-secondary-50': baseColors.light.secondary50,
    '--color-success': baseColors.light.success,
    '--color-tertiary-100': baseColors.light.tertiary100,
    '--color-tertiary-30': baseColors.light.tertiary30,
    '--color-tertiary-50': baseColors.light.tertiary50,
    '--color-text-100': baseColors.light.text100,
    '--color-text-30': baseColors.light.text30,
    '--color-text-50': baseColors.light.text50,
    '--color-text-70': baseColors.light.text70,
    '--color-text-90': baseColors.light.text90,
    '--color-warning': baseColors.light.warning,
  }),
}

export const themeColors = baseColors
